name: GitHub Updates to LinkedIn Page

on:
  schedule:
    - cron: "0 19 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull origin main

      - name: Install Python dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Parse feed and post to LinkedIn Page
        run: |
          . venv/bin/activate
          python src/github_updates_to_linkedin.py
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_ORG_ID: ${{ secrets.LINKEDIN_ORG_ID }}

      - name: Commit and Push posted_items.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add posted_items.json
          git commit -m "Update posted_items.json - GitHub Updates" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
